api_secret_key = "api_secret_key" # please set me up!

[destination.snowflake.credentials]
database = "job_ads" # please set me up!
password = "74w&vY3jzkqN9jj4" # please set me up!
username = "jassef" # please set me up!
host = "xs66603.west-europe.azure"
warehouse = "DEV_WH" # please set me up!
role = "JOB_ADS_DBT_ROLE" # please set me up!