models:
    - name: dim_employer
      columns: 
        - name: employer_id
          data_tests:
            - unique
            - not_null

        - name: workplace_city
          data_tests:
            - not_null
    
    - name: dim_job_details
      columns:
        - name: job_details_id
          data_tests:
          - unique
          - not_null
        - name: headline
          data_tests:
            - not_null
    - name: fct_job_ads
      columns:
        - name: job_details_key
          data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
        - name: relevance
          data_tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 0
                max_value: 1
                config:
                  severity: warn