USE WAREHOUSE MARKETING_WH;

USE ROLE ACCOUNTADMIN; 

CREATE DATABASE IF NOT EXISTS Parking;

USE Parking;

CREATE SCHEMA STAGING;
GRANT USAGE ON DATABASE Parking to ROLE marketing_dlt_role;
GRANT USAGE ON SCHEMA Parking.staging TO ROLE marketing_dlt_role;