USE ROLE SYSADMIN;

USE DATABASE JOB_ADS;

CREATE SCHEMA IF NOT EXISTS marts;

SHOW SCHEMAS IN DATABASE JOB_ADS;

USE ROLE SECURITYADMIN;

GRANT USAGE,
CREATE TABLE,
CREATE VIEW ON SCHEMA JOB_ADS.marts TO ROLE job_ads_dbt_role;

GRANT SELECT,
INSERT,
UPDATE,
DELETE ON ALL TABLES IN SCHEMA job_ads.marts TO ROLE job_ads_dbt_role;

GRANT SELECT ON ALL VIEWS IN SCHEMA job_ads.marts TO ROLE job_ads_dbt_role;

GRANT SELECT,
INSERT,
UPDATE,
DELETE ON FUTURE TABLES IN SCHEMA job_ads.marts TO ROLE job_ads_dbt_role;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA job_ads.marts TO ROLE job_ads_dbt_role;

USE ROLE job_ads_dbt_role;

SHOW GRANTS ON SCHEMA job_ads.marts;

USE SCHEMA job_ads.marts;

CREATE TABLE test (id integer);

SHOW TABLES;

DROP TABLE test;